version: 2
jobs:
  test:
    working_directory: ~/fluent/fluentd-website
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      # https://circleci.com/developer/images/image/cimg/ruby
      - image: cimg/ruby:3.4
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
      - run: 'bundle config set path vendor/bundle'
      - run: 'bundle check || bundle install --jobs=4 --retry=3'
      #- run:
      #    command: bundle exec ruby -E UTF-8 scripts/test_5xx.rb
      #    environment:
      #      RAILS_ENV: test
      #      RACK_ENV: test

  deploy:
    working_directory: ~/fluent/fluentd-website
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: cimg/ruby:3.4
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: Deploy
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            $REFRESH_CACHE_COMMAND

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
